from typing import TypedDict, Optional, List, Dict, Any, Union

class MLState(TypedDict):
    """Main state object managing data trajectories across decoupled nodes."""
    
    # ----------------------------------------------------------------
    # Host Environment Inputs & Cloned Workspace Directories
    # ----------------------------------------------------------------
    target_path: str                 # Original directory folder provided by host prompt
    clone_workspace: str             # Isolated workspace path, e.g., .../.temp/ml_agent_6279f94e
    all_files: List[str]             # Absolute paths of raw files copied into the datasets/ folder
    
    # Clean split dataset file paths generated inside processed-datasets/
    train_path: str                  # Path to processed-datasets/train-dataset.{extension}
    test_path: str                   # Path to processed-datasets/test-dataset.{extension}
    
    # ----------------------------------------------------------------
    # Target Suggestion Metadata (Step 1 of Selection Phase)
    # ----------------------------------------------------------------
    # Array of objects: [{"target_name": "...", "description": "...", "weight": 0.95}]
    target_recommendations: List[Dict[str, Any]] 
    chosen_target: Optional[Union[str, List[str]]]  # Selected target feature column(s) (supports string or list format)
    
    # ----------------------------------------------------------------
    # Algorithm Selection Metadata (Step 2 of Selection Phase)
    # ----------------------------------------------------------------
    problem_type: Optional[str]      # Inferred task: "Classification" or "Regression"
    
    # Array of objects: [{"algorithm_name": "...", "weight": 0.95, "description": "..."}]
    algorithm_recommendations: List[Dict[str, Any]] 
    chosen_algorithm: Optional[str]  # Selected model architecture confirmed by user (e.g., "XGBoostClassifier")
    
    # ----------------------------------------------------------------
    # ML Code Generation & Sandbox Architecture Extensions
    # ----------------------------------------------------------------
    generated_code_rationale: Optional[str]  # Architectural explanation generated by the LLM code planner
    generated_code_script: Optional[str]     # Pure, stripped, execution-ready Python script code string
    script_execution_success: Optional[bool] # Execution gate verification flag: True if code executed with 0 errors
    runtime_stdout: Optional[str]            # Captured terminal logs, outputs, and prints from script run
    runtime_stderr: Optional[str]            # Captured Python runtime error stack traces if execution crashes
    
    # ----------------------------------------------------------------
    # Local Self-Healing Loop Feedbacks
    # ----------------------------------------------------------------
    is_data_valid: bool              # Validation flag populated by the AI Validator Node (True/False)
    consolidation_feedback: Optional[str] # Holds traceback logs or errors if cleaner/combiner/auditor nodes fail
    retry_counters: Dict[str, int]   # Keeps track of loop iterations, e.g., {"ingestion_loop": 0, "generation_loop": 0}
    
    # ----------------------------------------------------------------
    # Token Tracking Operations
    # ----------------------------------------------------------------
    token_count: int                 # Global continuous cumulative token burn tracker
    node_tokens: Dict[str, int]      # Local dictionary mapping node keys to token values