"""ML State Contract.

Defines the centralized state tracking dictionary topology managing variables, 
file pathways, and model orchestration boundaries across decoupled pipeline nodes.
"""

from typing import Any, Dict, List, Optional, TypedDict, Union


class MLState(TypedDict):
    """Main state object managing data trajectories across decoupled nodes."""

    # ----------------------------------------------------------------
    # Host Environment Inputs & Cloned Workspace Directories
    # ----------------------------------------------------------------
    target_path: str                  # Original directory folder provided by host prompt
    clone_workspace: str              # Isolated workspace path, e.g., .../.temp/ml_agent_6279f94e
    all_files: List[str]              # Absolute paths of raw files copied into the datasets/ folder
    
    # Clean split dataset file paths generated inside processed-datasets/
    train_path: str                  # Path to processed-datasets/train_dataset.csv
    test_path: str                   # Path to processed-datasets/test_dataset.csv
    
    # ----------------------------------------------------------------
    # Analytics & Selection Phase Metadata
    # ----------------------------------------------------------------
    target_recommendations: List[Dict[str, Any]]
    chosen_target: Optional[Union[str, List[str]]]  # Selected target feature column(s)
    problem_type: Optional[str]       # Inferred task: "Classification" or "Regression"
    algorithm_recommendations: List[Dict[str, Any]]
    chosen_algorithm: Optional[str]   # Selected model architecture (e.g., "XGBoostClassifier")
    
    # ----------------------------------------------------------------
    # 📦 ML Code Generation & Infrastructure Extensions
    # ----------------------------------------------------------------
    generated_code_rationale: Optional[str]   # Architectural explanation generated by LLM code planner
    train_script_code: Optional[str]         # Raw text string containing training execution source (train.py)
    evaluation_script_code: Optional[str]    # Raw text string containing 10-row inference layout source (main.py)
    workspace_readme_text: Optional[str]     # Specialized runbook user documentation markdown string
    script_execution_success: Optional[bool]  # Execution status tracking indicator flag
    runtime_stdout: Optional[str]             # Standard terminal logging trace capture
    runtime_stderr: Optional[str]             # Standard runtime trace crash exception log capture

    # ----------------------------------------------------------------
    # Local Self-Healing Loop Feedbacks
    # ----------------------------------------------------------------
    is_data_valid: bool               # Validation flag populated by the Dataset Auditor Node
    consolidation_feedback: Optional[str] # Holds traceback logs or errors if processing/healing cycles fail
    retry_counters: Dict[str, int]    # Keeps track of loop iterations: {"ingestion_loop": 0, "generation_loop": 0}
    
    # ----------------------------------------------------------------
    # Token Tracking Operations
    # ----------------------------------------------------------------
    token_count: int                  # Global continuous cumulative token burn tracker
    node_tokens: Dict[str, int]       # Local dictionary mapping specific node keys to token values